### ISSUE TITLE
Version Number?

### ISSUE THREAD

**Issue by michaelwayneharris87** [davosmith/moodle-grade_checklist#4]
Hi,

I'm a bit confused. The `version.php` file on the last commit of master says `2020101700`, and the Moodle compatible version says `3.4+`. But when I download from https://moodle.org/plugins/pluginversions.php?plugin=mod_checklist, I see that the version says `2020111400` and the moodle compatible version is `3.9+`.

We prefer to manage our plugins through git. Is there a way to download the `2020111400` version through git?

Thanks for your help!

**Comment by davosmith** [comment]
Yes - it's here:  https://github.com/davosmith/moodle-checklist

(in the activity module github repo, not the grade export repo).

**Comment by michaelwayneharris87** [comment]
Ohhh thank you! My mistake!
